"""Lessons,terms,questions and notes added.

Revision ID: 14a60b6fb9c6
Revises: 6fdca5d089ed
Create Date: 2025-07-28 18:42:27.822562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a60b6fb9c6'
down_revision: Union[str, Sequence[str], None] = '6fdca5d089ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_title', sa.String(), nullable=True),
    sa.Column('n_lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['n_lesson_id'], ['note_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_title', sa.String(), nullable=True),
    sa.Column('q_lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['q_lesson_id'], ['question_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['note_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('difficulty_category', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['question_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('notes')
    op.drop_table('question_terms')
    op.drop_table('note_terms')
    # ### end Alembic commands ###
